import {
    ElectionStatus,
    ElectionType,
    IOverviewSummary,
    ReferendumStatus,
} from '@election/shared';

export const MOCK_OVERVIEW: IOverviewSummary = {
    election: {
        id: 1,
        name: 'การเลือกตั้งสมาชิกสภาผู้แทนราษฎรเป็นการทั่วไป พ.ศ. 2566',
        electionDate: '2023-05-14T00:00:00.000Z',
        type: ElectionType.GENERAL,
        status: ElectionStatus.COUNTING,
        hasReferendum: true,
        totalEligibleVoters: 52395490,
        createdAt: '2023-01-01T00:00:00.000Z',
        updatedAt: '2023-05-14T18:00:00.000Z',
    },
    totalCounted: 312,
    countingPercentage: 78,
    parties: [
        {
            party: {
                id: 1,
                nameTh: 'ก้าวไกล',
                nameEn: 'Move Forward',
                abbreviation: 'ก.ก.',
                color: '#FF6B00',
                logoUrl: null,
                leaderName: 'พิธา ลิ้มเจริญรัตน์',
                leaderImageUrl: null,
                partyNumber: 29,
            },
            constituencySeats: 112,
            partyListSeats: 39,
            totalSeats: 151,
            totalVotes: 14484219,
            rank: 1,
        },
        {
            party: {
                id: 2,
                nameTh: 'เพื่อไทย',
                nameEn: 'Pheu Thai',
                abbreviation: 'พท.',
                color: '#E53935',
                logoUrl: null,
                leaderName: 'แพทองธาร ชินวัตร',
                leaderImageUrl: null,
                partyNumber: 4,
            },
            constituencySeats: 141,
            partyListSeats: 0,
            totalSeats: 141,
            totalVotes: 10934498,
            rank: 2,
        },
        {
            party: {
                id: 3,
                nameTh: 'ภูมิใจไทย',
                nameEn: 'Bhumjaithai',
                abbreviation: 'ภท.',
                color: '#00BCD4',
                logoUrl: null,
                leaderName: 'อนุทิน ชาญวีรกูล',
                leaderImageUrl: null,
                partyNumber: 11,
            },
            constituencySeats: 67,
            partyListSeats: 4,
            totalSeats: 71,
            totalVotes: 4720340,
            rank: 3,
        },
        {
            party: {
                id: 4,
                nameTh: 'พลังประชารัฐ',
                nameEn: 'Palang Pracharath',
                abbreviation: 'พปชร.',
                color: '#3949AB',
                logoUrl: null,
                leaderName: 'ประวิตร วงษ์สุวรรณ',
                leaderImageUrl: null,
                partyNumber: 27,
            },
            constituencySeats: 40,
            partyListSeats: 0,
            totalSeats: 40,
            totalVotes: 1919433,
            rank: 4,
        },
        {
            party: {
                id: 5,
                nameTh: 'รวมไทยสร้างชาติ',
                nameEn: 'United Thai Nation',
                abbreviation: 'รทสช.',
                color: '#1565C0',
                logoUrl: null,
                leaderName: 'พีระพันธุ์ สาลีรัฐวิภาค',
                leaderImageUrl: null,
                partyNumber: 25,
            },
            constituencySeats: 23,
            partyListSeats: 13,
            totalSeats: 36,
            totalVotes: 4033291,
            rank: 5,
        },
        {
            party: {
                id: 6,
                nameTh: 'ประชาธิปัตย์',
                nameEn: 'Democrat',
                abbreviation: 'ปชป.',
                color: '#0277BD',
                logoUrl: null,
                leaderName: 'จุรินทร์ ลักษณวิศิษฏ์',
                leaderImageUrl: null,
                partyNumber: 36,
            },
            constituencySeats: 22,
            partyListSeats: 3,
            totalSeats: 25,
            totalVotes: 925590,
            rank: 6,
        },
        {
            party: {
                id: 7,
                nameTh: 'ชาติไทยพัฒนา',
                nameEn: 'Chartthaipattana',
                abbreviation: 'ชทพ.',
                color: '#2E7D32',
                logoUrl: null,
                leaderName: 'วราวุธ ศิลปอาชา',
                leaderImageUrl: null,
                partyNumber: 5,
            },
            constituencySeats: 10,
            partyListSeats: 0,
            totalSeats: 10,
            totalVotes: 506905,
            rank: 7,
        },
        {
            party: {
                id: 8,
                nameTh: 'ไทยสร้างไทย',
                nameEn: 'Thai Sang Thai',
                abbreviation: 'ทสท.',
                color: '#7B1FA2',
                logoUrl: null,
                leaderName: 'สุดารัตน์ เกยุราพันธุ์',
                leaderImageUrl: null,
                partyNumber: 20,
            },
            constituencySeats: 6,
            partyListSeats: 0,
            totalSeats: 6,
            totalVotes: 315927,
            rank: 8,
        },
        {
            party: {
                id: 9,
                nameTh: 'เป็นธรรม',
                nameEn: 'Pen Tham',
                abbreviation: 'ปธ.',
                color: '#F57F17',
                logoUrl: null,
                leaderName: 'ชัยธวัช ตุลาธน',
                leaderImageUrl: null,
                partyNumber: 15,
            },
            constituencySeats: 0,
            partyListSeats: 9,
            totalSeats: 9,
            totalVotes: 1010156,
            rank: 9,
        },
        {
            party: {
                id: 10,
                nameTh: 'ชาติพัฒนากล้า',
                nameEn: 'Chat Pattana Kla',
                abbreviation: 'ชพก.',
                color: '#558B2F',
                logoUrl: null,
                leaderName: 'กรณ์ จาติกวณิช',
                leaderImageUrl: null,
                partyNumber: 33,
            },
            constituencySeats: 2,
            partyListSeats: 0,
            totalSeats: 2,
            totalVotes: 398198,
            rank: 10,
        },
    ],
    referendum: [
        {
            id: 1,
            electionId: 1,
            questionTh: 'ท่านเห็นชอบหรือไม่ที่จะให้มีการจัดทำรัฐธรรมนูญฉบับใหม่ โดยไม่แก้ไขหมวด 1 และหมวด 2?',
            questionEn: 'Do you agree to have a new constitution drafted, without amending Chapters 1 and 2?',
            descriptionTh: 'หมวด 1 บททั่วไป และหมวด 2 พระมหากษัตริย์ ซึ่งเป็นบทบัญญัติเกี่ยวกับสถาบันพระมหากษัตริย์',
            descriptionEn: 'Chapter 1 (General Provisions) and Chapter 2 (The King) contain provisions regarding the monarchy.',
            isEnabled: true,
            displayOrder: 1,
            status: ReferendumStatus.COUNTING,
            totalEligibleVoters: 52395490,
            totalVoters: 40868482,
            approveCount: 25730244,
            disapproveCount: 13847261,
            abstainCount: 1290977,
            badBallots: 0,
            countingProgress: 78,
            createdAt: '2023-05-14T00:00:00.000Z',
            updatedAt: '2023-05-14T18:00:00.000Z',
        },
    ],
    sections: [
        { id: 1, electionId: 1, sectionKey: 'hero_banner', titleTh: 'แบนเนอร์หลัก', titleEn: 'Hero Banner', sectionType: 'HERO', isEnabled: true, displayOrder: 1, config: null, createdAt: '', updatedAt: '' },
        { id: 2, electionId: 1, sectionKey: 'top_parties', titleTh: 'พรรคอันดับต้น', titleEn: 'Top Parties', sectionType: 'CARDS', isEnabled: true, displayOrder: 2, config: null, createdAt: '', updatedAt: '' },
        { id: 3, electionId: 1, sectionKey: 'referendum', titleTh: 'ผลประชามติ', titleEn: 'Referendum Results', sectionType: 'REFERENDUM', isEnabled: true, displayOrder: 3, config: null, createdAt: '', updatedAt: '' },
        { id: 4, electionId: 1, sectionKey: 'party_leaderboard', titleTh: 'ตารางอันดับพรรค', titleEn: 'Party Leaderboard', sectionType: 'TABLE', isEnabled: true, displayOrder: 4, config: null, createdAt: '', updatedAt: '' },
        { id: 5, electionId: 1, sectionKey: 'counting_progress', titleTh: 'ความคืบหน้าการนับคะแนน', titleEn: 'Counting Progress', sectionType: 'PROGRESS', isEnabled: true, displayOrder: 5, config: null, createdAt: '', updatedAt: '' },
        { id: 6, electionId: 1, sectionKey: 'live_ticker', titleTh: 'ข่าวสารด่วน', titleEn: 'Live Ticker', sectionType: 'TICKER', isEnabled: true, displayOrder: 8, config: null, createdAt: '', updatedAt: '' },
    ],
    lastUpdated: new Date().toISOString(),
};

export const MOCK_TICKER_ITEMS = [
    'ก้าวไกลนำโด่งด้วย 151 ที่นั่ง ขณะที่นับคะแนนแล้ว 78%',
    'เพื่อไทยรั้งอันดับ 2 ด้วย 141 ที่นั่ง',
    'ผลประชามติเบื้องต้น: เห็นชอบ 63% | ไม่เห็นชอบ 33.9%',
    'ภูมิใจไทยคว้า 71 ที่นั่ง รั้งอันดับ 3',
    'ผู้มาใช้สิทธิ์ประมาณ 75.22% ของผู้มีสิทธิ์ทั้งหมด',
    'นับคะแนนแล้ว 312 จาก 400 เขต',
];
